### ISSUE TITLE
Failed Migration to 9.0

### ISSUE THREAD

**Issue by RainGigel** [SecurityRiskAdvisors/vectr-sql-migration#1]
I'm trying to get my vectr server from 8.7.1 to 9.0 and I'm gettting the "exited with code 1" istead of "0"

I think the issue is in this part of the log

```
vectr-migration_1  | 2024-04-10 09:12:29,372 WARN [org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor] - DB: TIMESTAMP(12) WITH TIME ZONE precision reduced to maximum allowed, 6 (SQL State: 22023 - Error Code: 0)
vectr-migration_1  | 2024-04-10 09:12:29,381 WARN [org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor] - DB: TIMESTAMP(12) WITH TIME ZONE precision reduced to maximum allowed, 6 (SQL State: 22023 - Error Code: 0)
vectr-migration_1  | 2024-04-10 09:12:44,983 ERROR [org.flywaydb.core.internal.command.DbMigrate] - Migration of schema "vectr" to version "2.02 - mongo to rdb" failed! Changes successfully rolled back.
vectr-migration_1  | 2024-04-10 09:12:45,047 ERROR [org.springframework.boot.SpringApplication] - Application run failed
vectr-migration_1  | java.lang.IllegalStateException: Failed to execute ApplicationRunner
```

Buf to be safe I've posted the entire log...  everything is going fine up until the "docker compose up" the mongodump and extraction part is fine and there is no issues there.

What am I doing wrong ?

```
# docker-compose up
WARNING: The VECTR_HOSTNAME variable is not set. Defaulting to a blank string.
Creating network "vectrmigration1_vectrmigration_bridge" with the default driver
Creating volume "vectrmigration1-vectr-rdb" with default driver
Creating volume "vectrmigration1-vectr-db" with default driver
Pulling vectr-postgres (postgres:15)...
15: Pulling from library/postgres
8a1e25ce7c4f: Pull complete
b2be002daccf: Pull complete
71dff0956c31: Pull complete
962627501404: Pull complete
c23077a7a05a: Pull complete
40632b8e7084: Pull complete
cfbec5f1dac7: Pull complete
d1743de7c97b: Pull complete
c9cde040a07c: Pull complete
3a23a8d46005: Pull complete
f499f39f0f2d: Pull complete
2cf0f5381fa5: Pull complete
89f512733a11: Pull complete
45deb7326cc7: Pull complete
Digest: sha256:ea40a028dd42740d6cff34135ff6b3119ff7ce0ed60120d992216456b5987fe7
Status: Downloaded newer image for postgres:15
Pulling vectr-migration (securityriskadvisors/vectr-sqlmigration:latest)...
latest: Pulling from securityriskadvisors/vectr-sqlmigration
23828d760c7b: Pull complete
77cdbc1da0db: Pull complete
e153ab5e1875: Pull complete
fc4c1e19b49f: Pull complete
Digest: sha256:14dda31c029b451469e5c45a84182e8a660c9b8396d42dfe227cc90731bdd390
Status: Downloaded newer image for securityriskadvisors/vectr-sqlmigration:latest
Creating vectrmigration1_vectr-mongo_1 ... 
Creating vectrmigration1_vectr-postgres_1 ... 
Creating vectrmigration1_vectr-postgres_1
Creating vectrmigration1_vectr-mongo_1 ... done
Creating vectrmigration1_vectr-migration_1 ... 
Creating vectrmigration1_vectr-migration_1 ... done
Attaching to vectrmigration1_vectr-postgres_1, vectrmigration1_vectr-mongo_1, vectrmigration1_vectr-migration_1
vectr-postgres_1   | WARNING: no logs are available with the 'none' log driver
vectr-mongo_1      | WARNING: no logs are available with the 'none' log driver
vectr-migration_1  | Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
vectr-migration_1  |    _____ ____  ___       ___   __  __________  __   __  _________________  ___  ______________  _   __
vectr-migration_1  |   / ___// __ \/   |     /   | / / / /_  __/ / / /  /  |/  /  _/ ____/ __ \/   |/_  __/  _/ __ \/ | / /
vectr-migration_1  |   \__ \/ /_/ / /| |    / /| |/ / / / / / / /_/ /  / /|_/ // // / __/ /_/ / /| | / /  / // / / /  |/ /
vectr-migration_1  |  ___/ / _, _/ ___ |   / ___ / /_/ / / / / __  /  / /  / // // /_/ / _, _/ ___ |/ / _/ // /_/ / /|  /
vectr-migration_1  | /____/_/ |_/_/  |_|  /_/  |_\____/ /_/ /_/ /_/  /_/  /_/___/\____/_/ |_/_/  |_/_/ /___/\____/_/ |_/
vectr-migration_1  | 
vectr-migration_1  | Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
vectr-migration_1  |    _____ ____  ___       _    ________________________     __  _________________  ___  ______________  _   __
vectr-migration_1  |   / ___// __ \/   |     | |  / / ____/ ____/_  __/ __ \   /  |/  /  _/ ____/ __ \/   |/_  __/  _/ __ \/ | / /
vectr-migration_1  |   \__ \/ /_/ / /| |     | | / / __/ / /     / / / /_/ /  / /|_/ // // / __/ /_/ / /| | / /  / // / / /  |/ /
vectr-migration_1  |  ___/ / _, _/ ___ |     | |/ / /___/ /___  / / / _, _/  / /  / // // /_/ / _, _/ ___ |/ / _/ // /_/ / /|  /
vectr-migration_1  | /____/_/ |_/_/  |_|     |___/_____/\____/ /_/ /_/ |_|  /_/  /_/___/\____/_/ |_/_/  |_/_/ /___/\____/_/ |_/
vectr-migration_1  | 
vectr-migration_1  | 2024-04-10 09:12:29,372 WARN [org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor] - DB: TIMESTAMP(12) WITH TIME ZONE precision reduced to maximum allowed, 6 (SQL State: 22023 - Error Code: 0)
vectr-migration_1  | 2024-04-10 09:12:29,381 WARN [org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor] - DB: TIMESTAMP(12) WITH TIME ZONE precision reduced to maximum allowed, 6 (SQL State: 22023 - Error Code: 0)
vectr-migration_1  | 2024-04-10 09:12:44,983 ERROR [org.flywaydb.core.internal.command.DbMigrate] - Migration of schema "vectr" to version "2.02 - mongo to rdb" failed! Changes successfully rolled back.
vectr-migration_1  | 2024-04-10 09:12:45,047 ERROR [org.springframework.boot.SpringApplication] - Application run failed
vectr-migration_1  | java.lang.IllegalStateException: Failed to execute ApplicationRunner
vectr-migration_1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765) [spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) [spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    at com.sra.vectrsqlmigration.Migration.main(Migration.java:99) [classes!/:?]
vectr-migration_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
vectr-migration_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
vectr-migration_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
vectr-migration_1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
vectr-migration_1  |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [vectr-migration.jar:?]
vectr-migration_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) [vectr-migration.jar:?]
vectr-migration_1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [vectr-migration.jar:?]
vectr-migration_1  |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [vectr-migration.jar:?]
vectr-migration_1  | Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: SQL State  : 22021
vectr-migration_1  | Error Code : 0
vectr-migration_1  | Message    : ERROR: invalid byte sequence for encoding "UTF8": 0x00
vectr-migration_1  |   Where: unnamed portal parameter $1
vectr-migration_1  | 
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:385) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at com.sra.vectrsqlmigration.Migration.migrate(Migration.java:336) ~[classes!/:?]
vectr-migration_1  |    at com.sra.vectrsqlmigration.Migration.run(Migration.java:93) ~[classes!/:?]
vectr-migration_1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    ... 13 more
vectr-migration_1  | Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO env_attack_log_entry(content, log_level, log_type, log_time, env_attack_log_procedure_id) VALUES(('E'), ('STDERR'), ('console'), ('2024-01-05 12:48:55+00'), ('175'::int4))
vectr-migration_1  | RETURNING "id" was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00
vectr-migration_1  |   Where: unnamed portal parameter $1  Call getNextException to see other errors in the batch.
vectr-migration_1  |    at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2413) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:579) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:912) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:936) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1733) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.addAttackLogEntries(ENVAttackLogBEMigrator.java:421) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.parseCampaignLogEntries(ENVAttackLogBEMigrator.java:241) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.parseTopLevelEntities(ENVAttackLogBEMigrator.java:181) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.parseAndPersistLogContents(ENVAttackLogBEMigrator.java:120) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrations.V2_02__mongo_to_rdb.migrate(V2_02__mongo_to_rdb.java:695) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:62) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at com.sra.vectrsqlmigration.Migration.migrate(Migration.java:336) ~[classes!/:?]
vectr-migration_1  |    at com.sra.vectrsqlmigration.Migration.run(Migration.java:93) ~[classes!/:?]
vectr-migration_1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    ... 13 more
vectr-migration_1  | Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
vectr-migration_1  |   Where: unnamed portal parameter $1
vectr-migration_1  |    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:579) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:912) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:936) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1733) ~[postgresql-42.7.2.jar!/:42.7.2]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.addAttackLogEntries(ENVAttackLogBEMigrator.java:421) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.parseCampaignLogEntries(ENVAttackLogBEMigrator.java:241) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.parseTopLevelEntities(ENVAttackLogBEMigrator.java:181) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVAttackLogBEMigrator.parseAndPersistLogContents(ENVAttackLogBEMigrator.java:120) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at com.sra.vectr.model.rdb.migrations.V2_02__mongo_to_rdb.migrate(V2_02__mongo_to_rdb.java:695) ~[model-rdb-migrations-1.0.5.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:62) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.1.0.jar!/:?]
vectr-migration_1  |    at com.sra.vectrsqlmigration.Migration.migrate(Migration.java:336) ~[classes!/:?]
vectr-migration_1  |    at com.sra.vectrsqlmigration.Migration.run(Migration.java:93) ~[classes!/:?]
vectr-migration_1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-3.1.2.jar!/:3.1.2]
vectr-migration_1  |    ... 13 more
vectrmigration1_vectr-migration_1 exited with code 1
```

**Comment by SRAPSpencer** [comment]
@RainGigel This looks like an issue very specific to your dataset. We'll need more details around the way you use VECTR and how you're importing data. Can you email us at vectrops@sra.io so we can discuss privately?

**Comment by RainGigel** [comment]
After some great advice we finally migrated to 9.0.2

At the step "RUN Migration" 

1. docker pull securityriskadvisors/vectr-sqlmigration:latest
2. docker compose up
3. You should get the:
vectr-migration_1  | DONE MIGRATION
vectrmigration1_vectr-migration_1 exited with code 0`
4. docker compose down -v 

Then continue with the steps from "Load into VECTR 9.0"

This fixed my issue.
