### ISSUE TITLE
Previously valid field value no longer valid

### ISSUE THREAD

**Issue by storebrand-mats** [SecurityRiskAdvisors/vectr-sql-migration#2]
## Insert below error from docker runtime log
```
vectrmigration1-vectr-postgres-1   | 2024-05-10 07:40:46.006 UTC [73] ERROR:  invalid input value for enum attack_vector: "adjacent network"
vectrmigration1-vectr-postgres-1   | 2024-05-10 07:40:46.006 UTC [73] CONTEXT:  unnamed portal parameter $16 = '...'
vectrmigration1-vectr-postgres-1   | 2024-05-10 07:40:46.006 UTC [73] STATEMENT:  INSERT INTO env_test_case (cl_test_case_id, name, description, operator_guidance, detection_guidance, prevention_guidance,     threat_references, sort_order, attack_technique_id, phase_id, capec_id, privilege_required,     attack_sophistication, attack_stealth, internal_external, attack_vector, technique_name, icon,     created_at, updated_at,     automation_cmd, automation_executor, automation_cleanup, automation_cleanup_executor,     env_campaign_id, outcome_notes, cl_outcome_id, status_id) VALUES  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28)
vectrmigration1-vectr-postgres-1   |    RETURNING "id"
vectrmigration1-vectr-migration-1  | java.sql.BatchUpdateException: Batch entry 65 INSERT INTO env_test_case (cl_test_case_id, name, description, operator_guidance, detection_guidance, prevention_guidance,     threat_references, sort_order, attack_technique_id, phase_id, capec_id, privilege_required,     attack_sophistication, attack_stealth, internal_external, attack_vector, technique_name, icon,     created_at, updated_at,     automation_cmd, automation_executor, automation_cleanup, automation_cleanup_executor,     env_campaign_id, outcome_notes, cl_outcome_id, status_id) VALUES  (('5ec16a0b-b799-4784-b151-5dadb297d4f7'::uuid), ('Encrypt a large amount of files'), ('Encrypt a large amount of files on disk to simulate ransomware behavior.'), ('CMD> {{ ransomware_binary }}'), ?, ?, ?, ('0'::int4), ('T1486'), ('5f453ab7-7447-4d48-85bb-c092111b10a5'::uuid), (NULL), ('FALSE'), ('minimal'), ('low'), ('internal'), ('adjacent network'), ('Data Encrypted for Impact'), ('icons/T1486.svg'), ('2024-01-24 13:16:37.238+00'), ('2024-03-14 12:15:33.148+00'), (''), ('command_prompt'), (NULL), (NULL), ('80'::int4), (''), ('fe631215-c4ec-3098-b93f-01d85612c104'::uuid), ('4'::int4))
vectrmigration1-vectr-migration-1  | RETURNING "id" was aborted: ERROR: invalid input value for enum attack_vector: "adjacent network"
vectrmigration1-vectr-migration-1  |   Where: unnamed portal parameter $16 = '...'  Call getNextException to see other errors in the batch.
vectrmigration1-vectr-migration-1  |    at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
vectrmigration1-vectr-migration-1  |    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2413)
vectrmigration1-vectr-migration-1  |    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:579)
vectrmigration1-vectr-migration-1  |    at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:912)
vectrmigration1-vectr-migration-1  |    at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:936)
vectrmigration1-vectr-migration-1  |    at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1733)
vectrmigration1-vectr-migration-1  |    at com.sra.vectr.model.rdb.migrationutils.v2.env.ENVTestCaseBEMigrator.insertData(ENVTestCaseBEMigrator.java:296)
vectrmigration1-vectr-migration-1  |    at com.sra.vectr.model.rdb.migrations.V2_02__mongo_to_rdb.migrate(V2_02__mongo_to_rdb.java:591)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:62)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215)
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.migrate(Migration.java:336)
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.run(Migration.java:93)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.main(Migration.java:99)
vectrmigration1-vectr-migration-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
vectrmigration1-vectr-migration-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
vectrmigration1-vectr-migration-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
vectrmigration1-vectr-migration-1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
vectrmigration1-vectr-migration-1  | Caused by: org.postgresql.util.PSQLException: ERROR: invalid input value for enum attack_vector: "adjacent network"
vectrmigration1-vectr-migration-1  |   Where: unnamed portal parameter $16 = '...'
vectrmigration1-vectr-migration-1  |    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
vectrmigration1-vectr-migration-1  |    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
vectrmigration1-vectr-migration-1  |    ... 43 more
vectrmigration1-vectr-migration-1  | 2024-05-10 07:40:46,017 ERROR [org.flywaydb.core.internal.command.DbMigrate] - Migration of schema "vectr" to version "2.02 - mongo to rdb" failed! Changes successfully rolled back.
vectrmigration1-vectr-migration-1  | 2024-05-10 07:40:46,073 ERROR [org.springframework.boot.SpringApplication] - Application run failed
vectrmigration1-vectr-migration-1  | java.lang.IllegalStateException: Failed to execute ApplicationRunner
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765) [spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) [spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.main(Migration.java:99) [classes!/:?]
vectrmigration1-vectr-migration-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
vectrmigration1-vectr-migration-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
vectrmigration1-vectr-migration-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
vectrmigration1-vectr-migration-1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [vectr-migration.jar:?]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) [vectr-migration.jar:?]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [vectr-migration.jar:?]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [vectr-migration.jar:?]
vectrmigration1-vectr-migration-1  | Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration failed !
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:382) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.migrate(Migration.java:336) ~[classes!/:?]
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.run(Migration.java:93) ~[classes!/:?]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    ... 13 more
vectrmigration1-vectr-migration-1  | Caused by: org.flywaydb.core.api.FlywayException: Migration failed !
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:76) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.migrate(Migration.java:336) ~[classes!/:?]
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.run(Migration.java:93) ~[classes!/:?]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    ... 13 more
vectrmigration1-vectr-migration-1  | Caused by: java.lang.NullPointerException: Cannot invoke "com.sra.vectr.model.rdb.migrationutils.v2.TestCaseMigrationData.getMetadataMap()" because "envTestCaseMigrationData" is null
vectrmigration1-vectr-migration-1  |    at com.sra.vectr.model.rdb.migrations.V2_02__mongo_to_rdb.migrate(V2_02__mongo_to_rdb.java:594) ~[model-rdb-migrations-1.0.6.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:62) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:54) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96) ~[flyway-database-postgresql-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.1.0.jar!/:?]
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.migrate(Migration.java:336) ~[classes!/:?]
vectrmigration1-vectr-migration-1  |    at com.sra.vectrsqlmigration.Migration.run(Migration.java:93) ~[classes!/:?]
vectrmigration1-vectr-migration-1  |    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-3.1.2.jar!/:3.1.2]
vectrmigration1-vectr-migration-1  |    ... 13 more
vectrmigration1-vectr-mongo-1      | 2024-05-10T07:40:46.156+0000 I  NETWORK  [conn70] end connection 10.1.27.4:40166 (5 connections now open)
vectrmigration1-vectr-mongo-1      | 2024-05-10T07:40:46.156+0000 I  NETWORK  [conn17] end connection 10.1.27.4:45176 (3 connections now open)
vectrmigration1-vectr-mongo-1      | 2024-05-10T07:40:46.156+0000 I  NETWORK  [conn69] end connection 10.1.27.4:40154 (4 connections now open)
vectrmigration1-vectr-mongo-1      | 2024-05-10T07:40:46.156+0000 I  NETWORK  [conn19] end connection 10.1.27.4:45196 (0 connections now open)
vectrmigration1-vectr-mongo-1      | 2024-05-10T07:40:46.156+0000 I  NETWORK  [conn68] end connection 10.1.27.4:40160 (2 connections now open)
vectrmigration1-vectr-mongo-1      | 2024-05-10T07:40:46.156+0000 I  NETWORK  [conn18] end connection 10.1.27.4:45186 (1 connection now open)
vectrmigration1-vectr-migration-1 exited with code 1
```

Afaik `"adjacent network"` used to be a valid value for `attack_vector`, but this no longer seems to be the case in 9.*

Manually changing the attack vector from "Adjacent network" to "Network" in GUI and then re-running the migration works, but is this intentional?

**Comment by SRAPSpencer** [comment]
Thanks for reporting this here, we're aware of the issue and will try to address this with a new version of the tool. We're currently in a focus window for our next VECTR release and it may be a few weeks until we can address this.
